server:
  port: 8000

security:
  jwt:
    # 30 sec
    expiration: 30000
    # change in docker runtime env variable
    # should not be public
    # must be 256 chars long
    secret: adminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadmina