db:
  name: warehouseman-warehouse
  username: "root"
  password: ""
  url: jdbc:mysql://localhost:3306/${db.name}
  driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8030
spring:
  datasource:
    driver-class-name: ${db.driver-class-name}
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /**


apis:
  warehouseman-product:
    url: http://localhost:8010
  warehouseman-auth:
    url: http://localhost:8000